### ISSUE TITLE
Got "Composer installed." even on composer error

### ISSUE THREAD

**Issue by michallohnisky** [AppsDevTeam/AfterDeploy#8]
How to reproduce it:

1. edit files in vendor
2. run afterdeploy
3. you can see "Composer installed." in green
4. run `composer install -o -n --no-dev` manually
5. you can see error "Source directory xxx has uncommitted changes." and composer is not installed

Expected behavior:

Option 1: In point 3. I should see "Composer returned an error" in red (by testing return code of composer command). **(I would go with this)**
Option 2: Add some parameter to composer, which will overwrite the changes in composer files.

**Comment by vvoody-** [comment]
#9
